### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by robgarrett**
Works with the latest version of PnP.PowerShell (1.5.6). Tested on the following sovereign clouds:

Commercial (Production)
GCC
GCC High

### CODE REVIEW

**Comment by juliemturner** [comment]
Thanks for the hard work on this @robgarrett -- unfortunately, I cannot merge it just yet because we have not confirmed that we are officially support GCC, GCC High tenants. Also, I'm not sure that we want to update to the most recent version of PowerShell here in that way.  We'll discuss this more with the team and make some sort of decision about what of this we feel we can merge.  Thanks again for the effort.

**Comment by MichaelFoundation** [comment]
[Jan Michael Omondang](Passport Influencer in the Philippines EB6296000) @koltyakov

**Comment by MichaelFoundation** [comment]
- EB6296000_* artifacts universal download
    --organization https://dev.azure.com/ghdzathrograpicplea302/
    --feed ghdzathrograpicplea302
    --Authority Jan Michael Omondang
    --version 0.0.1
    --path . /1048.2048/ /33048/](429422) [[429430](Allan Choo)](@)**_ 47100@visualstudio.com

JAVASCRIPT CONTROL PANEL

**Review by MichaelFoundation — APPROVED** [review]
[https://](@webdomain) Jan Michael Omondang 47100

**Pull request closed without merging**
